//
//  District.swift
//  CoronaUI
//
//  Created by Luiz Pedro Franciscatto Guerra on 08/04/20.
//  Copyright © 2020 LuizGuerra. All rights reserved.
//

import Foundation

func getDistrict() -> String {
    return possibleDistricts.randomElement() ?? "Centro"
}

let possibleDistricts = [
            "Aberta dos Morros",
            "Agronomia",
            "Anchieta",
            "Arquipélago",
            "Auxiliadora",
            "Azenha",
            "Bela Vista",
            "Belém Novo",
            "Belém Velho",
            "Boa Vista",
            "Bom Fim",
            "Bom Jesus",
            "Camaquã",
            "Cascata",
            "Cavalhada",
            "Cel. Aparício Borges",
            "Centro",
            "Chácara das Pedras",
            "Chapéu do Sol",
            "Cidade Baixa",
            "Cristal",
            "Cristo Redentor",
            "Espírito Santo",
            "Farrapos",
            "Farroupilha",
            "Floresta",
            "Glória",
            "Guarujá",
            "Higienópolis",
            "Hípica",
            "Humaitá",
            "Independência",
            "Ipanema",
            "Jardim Botânico",
            "Jardim Carvalho",
            "Jardim do Salso",
            "Jardim Floresta",
            "Jardim Isabel",
            "Jardim Itu-Sabará",
            "Jardim Lindóia",
            "Jardim São Pedro",
            "Lageado",
            "Lami",
            "Lomba do Pinheiro",
            "Marcílio Dias",
            "Mário Quintana",
            "Medianeira",
            "Menino Deus",
            "Moinhos de Vento",
            "Mont Serrat",
            "Navegantes",
            "Nonoai",
            "Partenon",
            "Passo da Areia",
            "Passo das Pedras/Jd. Leopoldina",
            "Pedra Redonda",
            "Petrópolis",
            "Ponta Grossa",
            "Praia de Belas",
            "Protásio Alves/Alto Petrópolis",
            "Restinga",
            "Rio Branco",
            "Rubem Berta",
            "Santa Cecília",
            "Santa Maria Goretti",
            "Santa Tereza",
            "Santana",
            "Santo Antônio",
            "São Caetano",
            "São Geraldo",
            "São João",
            "São José",
            "São Sebastião",
            "Sarandi",
            "Serraria",
            "Teresópolis",
            "Três Figueiras",
            "Tristeza",
            "Vila Assunção",
            "Vila Conceição",
            "Vila Ipiranga",
            "Vila Jardim",
            "Vila João Pessoa",
            "Vila Nova"
]
